# Generated by Django 5.2.8 on 2025-11-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_alter_producto_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen_url",
            field=models.URLField(
                blank=True,
                help_text="Ingresa la URL de una imagen (ej: https://ejemplo.com/imagen.jpg)",
                max_length=500,
                null=True,
                verbose_name="URL de Imagen",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="productos/",
                verbose_name="Imagen (Archivo)",
            ),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
